services:
  - type: web
    name: smartvision-attendance-portal
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    
    # Define environment variables
    envVars:
      - key: DATABASE_URL
        value: sqlite:////app/instance/smartvision.db
      - key: SECRET_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: "465"
      - key: SMTP_USERNAME
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: SMTP_USE_TLS
        value: "true"
      - key: SMTP_SENDER_EMAIL
        sync: false

